export let data = [
  {
    OrderID: 1,
    CustomerID: "PRASAD",
    EmployeeID: 101,
    OrderDate: new Date(8364186e5),
    ShipName: "Vins et alcools Chevalier",
    ShipCity: "Reims",
    ShipAddress: "59 rue de l Abbaye",
    ShipRegion: "CJ",
    ShipPostalCode: "51100",
    ShipCountry: "France",
    Freight: 32.38,
    Verified: !0,
  },
  {
    OrderID: 2,
    CustomerID: "JOHN",
    EmployeeID: 102,
    OrderDate: new Date(836505e6),
    ShipName: "Toms Spezialitäten",
    ShipCity: "Münster",
    ShipAddress: "Luisenstr. 48",
    ShipRegion: "CJ",
    ShipPostalCode: "44087",
    ShipCountry: "Germany",
    Freight: 11.61,
    Verified: !1,
  },
  {
    OrderID: 3,
    CustomerID: "JUSTIN",
    EmployeeID: 103,
    OrderDate: new Date(8379738e5),
    ShipName: "Rattlesnake Canyon Grocery",
    ShipCity: "Albuquerque",
    ShipAddress: "2817 Milton Dr.",
    ShipRegion: "NM",
    ShipPostalCode: "87110",
    ShipCountry: "USA",
    Freight: 48.29,
    Verified: !0,
  },
  {
    OrderID: 4,
    CustomerID: "RAMESH",
    EmployeeID: 104,
    OrderDate: new Date(8379738e5),
    ShipName: "Rattlesnake Canyon Grocery",
    ShipCity: "Albuquerque",
    ShipAddress: "2817 Milton Dr.",
    ShipRegion: "NM",
    ShipPostalCode: "87110",
    ShipCountry: "USA",
    Freight: 48.29,
    Verified: !0,
  },
  {
    OrderID: 5,
    CustomerID: "RUSSEL",
    EmployeeID: 105,
    OrderDate: new Date(8379738e5),
    ShipName: "Rattlesnake Canyon Grocery",
    ShipCity: "Albuquerque",
    ShipAddress: "2817 Milton Dr.",
    ShipRegion: "NM",
    ShipPostalCode: "87110",
    ShipCountry: "USA",
    Freight: 48.29,
    Verified: !0,
  },
  {
    OrderID: 6,
    CustomerID: "VIRAT",
    EmployeeID: 106,
    OrderDate: new Date(8379738e5),
    ShipName: "Rattlesnake Canyon Grocery",
    ShipCity: "Albuquerque",
    ShipAddress: "2817 Milton Dr.",
    ShipRegion: "NM",
    ShipPostalCode: "87110",
    ShipCountry: "USA",
    Freight: 48.29,
    Verified: !0,
  },
  {
    OrderID: 7,
    CustomerID: "ROHIT",
    EmployeeID: 107,
    OrderDate: new Date(8379738e5),
    ShipName: "Rattlesnake Canyon Grocery",
    ShipCity: "Albuquerque",
    ShipAddress: "2817 Milton Dr.",
    ShipRegion: "NM",
    ShipPostalCode: "87110",
    ShipCountry: "USA",
    Freight: 48.29,
    Verified: !0,
  },
  {
    OrderID: 8,
    CustomerID: "DHONI",
    EmployeeID: 108,
    OrderDate: new Date(8379738e5),
    ShipName: "Rattlesnake Canyon Grocery",
    ShipCity: "Albuquerque",
    ShipAddress: "2817 Milton Dr.",
    ShipRegion: "NM",
    ShipPostalCode: "87110",
    ShipCountry: "USA",
    Freight: 48.29,
    Verified: !0,
  },
  {
    OrderID: 9,
    CustomerID: "BUMRAH",
    EmployeeID: 109,
    OrderDate: new Date(8379738e5),
    ShipName: "Rattlesnake Canyon Grocery",
    ShipCity: "Albuquerque",
    ShipAddress: "2817 Milton Dr.",
    ShipRegion: "NM",
    ShipPostalCode: "87110",
    ShipCountry: "USA",
    Freight: 48.29,
    Verified: !0,
  },
  {
    OrderID: 10,
    CustomerID: "RAVINDRA",
    EmployeeID: 110,
    OrderDate: new Date(8379738e5),
    ShipName: "Rattlesnake Canyon Grocery",
    ShipCity: "Albuquerque",
    ShipAddress: "2817 Milton Dr.",
    ShipRegion: "NM",
    ShipPostalCode: "87110",
    ShipCountry: "USA",
    Freight: 48.29,
    Verified: !0,
  },
];
